main: me.erksterk.openeventsmc.Main
name: OpenEventsMC
version: Alpha2
author: ErkSterk
softdepend: [WorldEdit, PlaceholderAPI,Multiverse-Core]
commands:
  events:
    description: General commands for managing OpenEventsMC