main: me.erksterk.openeventsmc.Main
name: OpenEventsMC
version: Alpha1
author: ErkSterk
softdepend: [WorldEdit, PlaceholderAPI]
commands:
  events:
    description: General commands for managing OpenEventsMC